using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pos.Application.Common.Interfaces;
using Pos.Domain.Enums;
using Pos.Infrastructure.Persistence;

namespace Pos.Api.Controllers;

[ApiController]
[Route("api/products")]
[Authorize(Roles = "Manager,Admin")]
public sealed class EtimsProductsController : ControllerBase
{
    private readonly PosDbContext _context;
    private readonly IEtimsService _etimsService;
    private readonly IAuditService _auditService;

    public EtimsProductsController(
        PosDbContext context,
        IEtimsService etimsService,
        IAuditService auditService)
    {
        _context = context;
        _etimsService = etimsService;
        _auditService = auditService;
    }

    [HttpPost("{id:guid}/etims/register")]
    public async Task<IActionResult> Register(
        Guid id,
        CancellationToken cancellationToken)
    {
        var product = await _context.Products
            .Include(p => p.Category)
            .FirstOrDefaultAsync(
                p => p.Id == id && p.IsActive,
                cancellationToken);

        if (product is null)
            return NotFound(new { message = "Product not found or inactive." });

        if (string.IsNullOrWhiteSpace(product.EtimsItemClassificationCode))
        {
            return BadRequest(new
            {
                message =
                    "The product must first be assigned a KRA eTIMS " +
                    "classification before it can be registered."
            });
        }

        if (!string.IsNullOrWhiteSpace(product.EtimsItemCode))
        {
            return Conflict(new
            {
                message = "Product is already registered with eTIMS.",
                itemCd = product.EtimsItemCode,
                registeredAt = product.EtimsRegisteredAt
            });
        }

        var userIdValue =
            User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

        if (!Guid.TryParse(userIdValue, out var userId))
            return Unauthorized();

        /*
         * KRA's item-code structure is:
         *
         * KE + product type + packaging unit + quantity unit + 7-digit sequence
         *
         * For ordinary stocked POS products:
         *   2  = Finished Product
         *   NT = Net packaging unit
         *   U  = Pieces/item
         *
         * The sequence is generated by PostgreSQL so concurrent registrations
         * cannot accidentally receive the same number.
         */
        var sequence =
            await _context.Database
                .SqlQuery<long>(
                    $"""SELECT nextval('"EtimsItemCodeSequence"') AS "Value" """)
                .SingleAsync(cancellationToken);

        if (sequence > 9_999_999)
        {
            return StatusCode(
                StatusCodes.Status500InternalServerError,
                new
                {
                    message =
                        "The eTIMS item-code sequence has exceeded " +
                        "its seven-digit range."
                });
        }

        const string itemTypeCode = "2";
        const string originCountryCode = "KE";
        const string packagingUnitCode = "NT";
        const string quantityUnitCode = "U";

        var itemCode =
            $"{originCountryCode}" +
            $"{itemTypeCode}" +
            $"{packagingUnitCode}" +
            $"{quantityUnitCode}" +
            $"{sequence:0000000}";

        /*
         * The KRA classification's TaxTyCd is allowed to be null.
         * saveItem, however, requires taxTyCd.
         *
         * Map the POS tax class to the KRA tax type codes documented by KRA:
         *
         * Standard   -> B (16%)
         * ZeroRated  -> C (0%)
         * Exempt     -> A (Exempt)
         */
        var taxTypeCode = product.TaxClass switch
        {
            TaxClass.Standard => "B",
            TaxClass.ZeroRated => "C",
            TaxClass.Exempt => "A",
            _ => throw new InvalidOperationException(
                $"Unsupported POS tax class '{product.TaxClass}'.")
        };

        
    var request = new EtimsItemSaveRequest(
    product.EtimsItemClassificationCode,
    itemCode,
    itemTypeCode,
    product.Name,
    originCountryCode,
    packagingUnitCode,
    quantityUnitCode,
    taxTypeCode,
    product.SalePrice,
    "N",
    "Y",
    userId.ToString(),
    User.Identity?.Name ?? "POS",
    userId.ToString(),
    User.Identity?.Name ?? "POS",
    null,
    null,
    string.IsNullOrWhiteSpace(product.Barcode)
        ? null
        : product.Barcode)
{
    ItemStdNm = null,
    BtchNo = null
};
        var result =
            await _etimsService.SaveItemAsync(
                request,
                cancellationToken);

        if (!result.Success)
        {
            /*
             * The sequence number is deliberately not written to Product
             * until KRA accepts the item. A failed request therefore leaves
             * the product unregistered and the next attempt receives a new
             * sequence number.
             */
            return StatusCode(
                StatusCodes.Status502BadGateway,
                new
                {
                    message = "KRA eTIMS item registration failed.",
                    resultCode = result.ResultCode,
                    resultMessage = result.ResultMessage,
                    error = result.ErrorMessage,
                    itemCd = itemCode
                });
        }

        var registeredAt =
            result.ResultDate ??
            DateTime.UtcNow;

        product.EtimsItemCode = itemCode;
        product.EtimsItemTypeCode = itemTypeCode;
        product.EtimsOriginCountryCode = originCountryCode;
        product.EtimsPackagingUnitCode = packagingUnitCode;
        product.EtimsQuantityUnitCode = quantityUnitCode;
        product.EtimsRegisteredAt = registeredAt;
        product.EtimsRegisteredByUserId = userId;
        product.UpdatedAt = DateTime.UtcNow;

        await _context.SaveChangesAsync(cancellationToken);

        await _auditService.LogAsync(
            userId: userId,
            actionType: "PRODUCT_ETIMS_REGISTERED",
            entityName: "Product",
            entityId: product.Id,
            details:
                $"Registered product {product.Sku} - {product.Name} " +
                $"with eTIMS item code {itemCode}.");

        return Ok(new
        {
            productId = product.Id,
            sku = product.Sku,
            name = product.Name,
            itemCd = product.EtimsItemCode,
            itemClsCd = product.EtimsItemClassificationCode,
            taxTyCd = taxTypeCode,
            itemTyCd = product.EtimsItemTypeCode,
            orgnNatCd = product.EtimsOriginCountryCode,
            pkgUnitCd = product.EtimsPackagingUnitCode,
            qtyUnitCd = product.EtimsQuantityUnitCode,
            registeredAt = product.EtimsRegisteredAt,
            resultCode = result.ResultCode,
            resultMessage = result.ResultMessage
        });
    }
}