import type { CompleteSaleRequest } from "../types/sale";
import { db, type QueuedAction, type StockAdjustmentActionPayload } from "./db";
import { decrementLocalStock } from "./catalogCache";

/**
 * Every sale writes here FIRST, unconditionally, online or offline — see CheckoutPage's
 * submitSale: it still calls completeSale() directly for the immediate, synchronous
 * feedback (stock/till/discount validation), and only falls back to queueSale here when
 * that call fails to reach the server at all (isNetworkError). That's what keeps the
 * rich online validation UX intact while still making the offline path real, not a
 * separate rarely-exercised branch.
 *
 * clientTransactionId is generated by the CALLER (CheckoutPage.submitSale), once, before
 * completeSale is even attempted — not here. That's what lets a queued sale be safely
 * re-sent after reconnecting: SalesController.Complete checks this id first and returns
 * the original result instead of reprocessing if it's seen it before. It's also what
 * prevents a duplicate sale in the case where completeSale's request actually reached
 * the server and succeeded, but the response was lost (still classified as a network
 * error client-side) — queueing under the SAME id the failed completeSale call already
 * used means the server's idempotency check catches it as a replay, not a new sale.
 */
export async function queueSale(request: CompleteSaleRequest, registerId: string): Promise<string> {
  const { clientTransactionId } = request;

  const action: QueuedAction = {
    clientTransactionId,
    type: "Sale",
    payload: request,
    status: "Pending",
    createdAt: new Date().toISOString(),
    registerId,
    syncAttempts: 0,
  };

  await db.actionQueue.add(action);

  // Optimistic local stock update so the register's own next sale reflects it
  // immediately, without waiting for a round trip that might not happen for hours.
  for (const item of request.items) {
    await decrementLocalStock(item.productId, item.quantity);
  }

  return clientTransactionId;
}

export async function queueStockAdjustment(payload: StockAdjustmentActionPayload, registerId: string): Promise<string> {
  const clientTransactionId = crypto.randomUUID();

  await db.actionQueue.add({
    clientTransactionId,
    type: "StockAdjustment",
    payload,
    status: "Pending",
    createdAt: new Date().toISOString(),
    registerId,
    syncAttempts: 0,
  });

  return clientTransactionId;
}

export async function getPendingActionCount(): Promise<number> {
  return db.actionQueue.where("status").anyOf(["Pending", "Failed"]).count();
}

export async function getConflictedActions(): Promise<QueuedAction[]> {
  return db.actionQueue.where("status").equals("Conflict").toArray();
}

export async function getActionsNeedingApproval(): Promise<QueuedAction[]> {
  return db.actionQueue.where("status").equals("NeedsApproval").toArray();
}