// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pos.Infrastructure.Persistence;

#nullable disable

namespace Pos.Infrastructure.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260828030514_FixProductAndCategorySchema")]
     partial class FixProductAndCategorySchema : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
                    b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.HasKey("Id");
                    b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Pos.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("DefaultWarrantyMonths").HasColumnType("integer");
                    b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                    b.Property<Guid?>("ParentCategoryId").HasColumnType("uuid");
                    b.Property<bool>("RequiresSerialTracking").HasColumnType("boolean");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("ParentCategoryId");
                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Pos.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Barcode").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<Guid>("CategoryId").HasColumnType("uuid");
                    b.Property<decimal>("CostPrice").HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Description").HasColumnType("text");
                    b.Property<string>("ImageUrl").HasColumnType("text");
                    b.Property<bool>("IsActive").HasColumnType("boolean");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<int>("ReorderThreshold").HasColumnType("integer");
                    b.Property<decimal>("SalePrice").HasColumnType("decimal(18,2)");
                    b.Property<string>("Sku").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<int>("StockQuantity").HasColumnType("integer");
                    b.Property<int>("TaxClass").HasColumnType("integer");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                    b.Property<int?>("WarrantyMonthsOverride").HasColumnType("integer");
                    b.HasKey("Id");
                    b.HasIndex("Barcode").IsUnique().HasFilter("\"Barcode\" IS NOT NULL AND \"Barcode\" <> ''");
                    b.HasIndex("CategoryId");
                    b.HasIndex("Sku").IsUnique();
                    b.ToTable("Products");
                });

            // ... (The rest of your existing BuildTargetModel entities remain exactly as they were) ...
            // Just ensure there are NO "Up" or "Down" methods in this file.
#pragma warning restore 612, 618
        }
    }
}